### PR TITLE
Add support for showing a week or multiple days

### LINKED ISSUE #4: Last 7 days or custom length?
I'd love to see a weekly or x days option as opposed to a single day.

### PR DESCRIPTION
**Pull request by niklashigi**
Adds `--week` and `--days` options. Closes #4.

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
`--week` doesn't seem to work. 🤔 

```console
➜  devstats git:(multiple-days) ./bin/devstats --week

  Weekly report for Oct 15, 18 to Oct 15, 18

    GitHub         0 contributions made
    StackOverflow  0 reputation earned
    WakaTime       0 spent coding

➜  devstats git:(multiple-days) ./bin/devstats --days=4

  4-day report for Oct 12, 18 to Oct 15, 18

    GitHub         26 contributions made
    StackOverflow  0 reputation earned
    WakaTime       10 hours spent coding

➜  devstats git:(multiple-days) ./bin/devstats --days=7

  7-day report for Oct 9, 18 to Oct 15, 18

    GitHub         29 contributions made
    StackOverflow  -2 reputation earned
    WakaTime       14 hours spent coding
```

**Comment by OmgImAlexis** [comment]
Might be a good time to add tests?

**Comment by OmgImAlexis** [comment]
I also noticed in interactive mode with `days` the navigation should change to

```
[← Last x days] [→ Next x days] [Q Quit]
```

instead of
```
[← Previous day] [→ Next day] [Q Quit]
```

**Comment by niklashigi** [comment]
> `--week` doesn't seem to work

Well, weeks start with Monday in Germany, so the current week in that case actually only has one day so far. `devstats` should detect the user's preferred first week day, but I'm not sure what's the best way to do that.

> Might be a good time to add tests?

Um, probably. Not sure I have the time to add them at the moment though.

> I also noticed in interactive mode with `days` the navigation should change [...]

Not sure about this one since pressing the left and right keys doesn't actually jump x days, it only moves the x-day timeframe by one day.

**Pull request merged**
